version: 0.0
os: linux
files:
  - source: /wp-content
    destination: /var/www/html/wp-content
permissions:
  - object: /wp-content/uploads
    except: [/wp-content/uploads]
hooks:
  BeforeInstall:
    - location: deploy/before_install
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy/restart_server
      timeout: 300
      runas: root
